mode:
 - DocuMind
docuMind-model: "gemini/gemini-1.5-pro-latest"
docuMind-db: ".SourceSageAssets/DOCUMIND/Repository_summary.md"
docuMind-release-report: ".SourceSageAssets/RELEASE_REPORT/Report_v0.1.1.md"
docuMind-changelog: ".SourceSageAssets/Changelog/CHANGELOG_main.md"
docuMind-output: ".SourceSageAssets/DOCUMIND/RELEASE_NOTES_v0.1.1.md"
docuMind-prompt-output: ".SourceSageAssets/DOCUMIND/_PROMPT_v0.1.1.md"
repo-name: "I.R.I.S. - Intelligent Robotic Interaction System"
repo-version: "v0.1.1"

