name: 自動GitHubリリースノート生成

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 最新のタグを取得
        id: get_tag
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            echo "LATEST_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Python のセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: 依存関係のインストール
        run: |
          pip install -r .github/requirements.txt

      - name: GitHubリリースノートの生成
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LATEST_TAG: ${{ steps.get_tag.outputs.LATEST_TAG }}
          YOUR_PERSONAL_ACCESS_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
          YOUR_PERSONAL_ACCESS_TOKEN_IRIS: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN_IRIS }}
        run: python .github/scripts/generate_github_release_notes.py
