# .github/workflows/generate-release-notes.yml

name: 自動GitHubリリースノート生成

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:  # 手動実行のオプション
  
jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 最新のタグと1つ前のタグを取得
        id: get_tags
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${LATEST_TAG}^)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "PREVIOUS_TAG=${PREVIOUS_TAG}" >> $GITHUB_OUTPUT

      - name: 差分とREADMEの内容を取得
        id: get_diff_and_readme
        run: |
          DIFF=$(git diff ${{ steps.get_tags.outputs.PREVIOUS_TAG }}..${{ steps.get_tags.outputs.LATEST_TAG }} | sed 's/`/\\`/g')
          README=$(cat README.md | sed 's/`/\\`/g')
          echo "DIFF<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "README<<EOF" >> $GITHUB_OUTPUT
          echo "$README" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Python のセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: 依存関係のインストール
        run: |
          pip install -r requirements.txt

      - name: GitHubリリースノートの生成
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          DIFF: ${{ steps.get_diff_and_readme.outputs.DIFF }}
          README: ${{ steps.get_diff_and_readme.outputs.README }}
          LATEST_TAG: ${{ steps.get_tags.outputs.LATEST_TAG }}
          YOUR_PERSONAL_ACCESS_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
          YOUR_PERSONAL_ACCESS_TOKEN_IRIS: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN_IRIS }}
        run: python .github/scripts/generate_github_release_notes.py
